-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "countries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "countries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"country" text,
	"alpha3" text,
	CONSTRAINT "countries_country_key" UNIQUE("country")
);
--> statement-breakpoint
ALTER TABLE "countries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "draft" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "draft_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"draft_year" numeric,
	"draft_round" numeric,
	"draft_round_pick" numeric,
	"draft_overall" numeric,
	"original_team" bigint,
	"final_team" text
);
--> statement-breakpoint
ALTER TABLE "draft" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teams" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"team_name" text,
	"team_city" text,
	"team_state" text,
	"team_country" text,
	"start_date" date,
	"first_season" numeric,
	"last_season" numeric,
	CONSTRAINT "teams_team_name_key" UNIQUE("team_name")
);
--> statement-breakpoint
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "draft" ADD CONSTRAINT "draft_original_team_fkey" FOREIGN KEY ("original_team") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "teams_team_country_fkey" FOREIGN KEY ("team_country") REFERENCES "public"."countries"("country") ON DELETE no action ON UPDATE no action;
*/